export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const SET_NEW_PROJECT = 'SET_NEW_PROJECT';
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_BEGINNING_DATE = 'UPDATE_BEGINNING_DATE';
export const UPDATE_DUE_DATE = 'UPDATE_DUE_DATE';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const CLEAR_STORE = 'CLEAR_STORE';
